### ISSUE TITLE
Unnecessary allocations in miller_rabin

### ISSUE THREAD

**Issue by maurges** [mikelodder7/glass_pumpkin#14]
I'm trying to adapt this crate for no_std (and for use with crypto_bigint), and I'm wondering why in the miller_rabin test do we need to allocate all bases at once, instead of generating them on the fly with iterators?

**Comment by mikelodder7** [comment]
It’s not necessary, just haven’t returned to adapt this crate. I’d love to get this to work for crypto-bigint. However crypto-bigint doesn’t have all the necessary algorithms yet.
