### ISSUE TITLE
API was changed in recent release, and now downstream crates (unknown_order with rust backend) don't build

### ISSUE THREAD

**Issue by maurges** [mikelodder7/glass_pumpkin#18]
This is because in #17 I was incorrect to assume that the API doesn't change: I didn't notice that some functions were reexported, since I didn't use them myself. Sorry! :(

**Comment by Lonami** [comment]
Yeah `is_safe_prime` went from 

```rust
pub fn is_safe_prime(candidate: &BigUint) -> bool {
```

to

```rust
pub fn is_safe_prime<R: RngCore + ?Sized>(candidate: &BigUint, rng: &mut R) -> bool {
```

which breaks the `check` re-export:

https://github.com/mikelodder7/glass_pumpkin/blob/594dc61ad0d806fd0cdfa837a141fbaf1c960264/src/safe_prime.rs#L7

Ideally there would be a new release with 1.4.0 being yanked with this problem fixed, as it's a semver violation. I'm not sure what the impact is, but I can say I was affected.
